### ISSUE TITLE
Error: Can't resolve $ref relative to current document

### ISSUE THREAD

**Issue by moonray** [OpenAPI-Qraft/openapi-qraft#3]
When trying to generate Qraft services, I'm getting the following error with $ref relative to current document.
e.g.
```
 ✘  Can't resolve $ref: ENOENT: no such file or directory '/app/docs/#components/schemas/GlobalPagination'
Can't resolve $ref: ENOENT: no such file or directory '/app/docs/#components/schemas/GlobalPagination' Error: Can't resolve $ref: ENOENT: no such file or directory '/app/docs/#components/schemas/GlobalPagination'
    at validateAndBundle (file:///.npm/_npx/09ac6d5fc70ce7ef/node_modules/openapi-typescript/dist/lib/redoc.js:124:23)
    at async readSchema (file:///.npm/_npx/09ac6d5fc70ce7ef/node_modules/@openapi-qraft/cli/dist/lib/open-api/readSchema.js:9:20)
    at async writeOpenAPIServices (file:///.npm/_npx/09ac6d5fc70ce7ef/node_modules/@openapi-qraft/cli/dist/writeOpenAPIServices.js:13:20)
    at async Command.<anonymous> (file:///.npm/_npx/09ac6d5fc70ce7ef/node_modules/@openapi-qraft/cli/dist/bin.js:32:5)
```

Example snippet in my openapi file:
```
  /breadcrumbs/page/:
    get:
      summary: Returns paginated breadcrumbs
      tags:
        - Breadcrumbs
      responses:
        "200":
          description: A JSON object
          content:
            application/json:
              schema:
                type: object
                properties:
                  breadcrumbs:
                    type: array
                    description: a list of breadcrumbs from the segment
                    items:
                      $ref: "#/components/schemas/Breadcrumb"
                  pagination:
                    $ref: "#components/schemas/GlobalPagination"
        "403":
          $ref: "#/components/responses/403Forbidden"
```

**Comment by radist2s** [comment]
Hi, @moonray, thank you for the first issue! 🎉
According to the [spec](https://swagger.io/docs/specification/using-ref/#syntax), it looks like the syntax `$ref: "#components/schemas/GlobalPagination"` is invalid. Are you sure the `/` character is not missing after the `#`?

**Comment by radist2s** [comment]
@moonray, btw, the better guide currently exists only for the [`@openapi-qraft/react
`](https://github.com/OpenAPI-Qraft/openapi-qraft/blob/main/packages/react-client/README.md) package. 
This may not be obvious if you only use the README for `@openapi-qraft/cli`
